name: ict
channels:
  - pyg
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - torchvision
  - pytorch
  - pyg
  - torchaudio
  - cpuonly
  - pickleshare
  - libsodium
  - openssl
  - readline
  - certifi
  - entrypoints
  - ipython
  - packaging
  - six
  - psutil
  - backcall
  - wheel
  - libstdcxx-ng
  - jupyter_client
  - stack_data
  - decorator
  - matplotlib-inline
  - pyzmq
  - pip
  - sqlite
  - wcwidth
  - libgomp
  - tornado
  - pure_eval
  - python-dateutil
  - nest-asyncio
  - _openmp_mutex
  - zlib
  - prompt-toolkit
  - ptyprocess
  - pexpect
  - ncurses
  - executing
  - libffi
  - debugpy
  - pygments
  - setuptools
  - jedi
  - jupyter_core
  - _libgcc_mutex
  - tk
  - asttokens
  - pyparsing
  - traitlets
  - libgcc-ng
  - tzdata
  - ca-certificates
  - ld_impl_linux-64
  - zeromq
  - xz
  - parso
  - ipykernel
  - pip
  - pip:
    - click==8.0.4
    - dgl==0.9.1
    - distlib==0.3.6
    - pandas==1.5.0
    - pytz==2022.2.1
    - python-dateutil==2.8.2
    - ray==2.0.0
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - torchinfo==1.7.1
    - tqdm==4.64.1
